nawadaya_project/Controllers/StartLogicTestController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using nawadaya_project.Models;
using System.Security.Cryptography;
using System.Text;

namespace nawadaya_project.Controllers
{
    public class StartLogicTestController : Controller
    {
        private Nawadaya_Entities db = new Nawadaya_Entities();
        // GET: StartLogicTest
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult StartAndRedirect(long id, string link)
        {
            var key = "b14ca5898a4e4133bbce2ea2315a1916";
            using (DbContextTransaction transaction = db.Database.BeginTransaction())
            {
                try
                {
                    if (id != 0)
                    {
                        int active = 1;
                        var obj_pdf_problems = db.historical_invitation_progress.Where(x => x.fk_applicant_information_form == id && x.access_token == active).FirstOrDefault();//ini buat ambil objek/baris di kolom histrocal_invitation yang page logic_test masih bisa diakses(access_token=1) oleh pengguna (fk_applicant_information_form)
                        if (obj_pdf_problems.logic_test_first_access == 1) 
                        {
                            List<ms_logictest_result> list_latest_examinee = db.ms_logictest_result.Where(x => x.fk_applicant_information_form == (int)id).ToList();
                            var obj_latest_examinee_pk = list_latest_examinee.OrderBy(item => item.pk_logictest_result).Last();
                            TempData["link"] = link;
                            var latest_examinee_pk = obj_latest_examinee_pk.pk_logictest_result;
                            return RedirectToAction("UploadZIP", new { pk_id2 = EncryptString(key,latest_examinee_pk.ToString())  });
                        }
                        //ms_logictest_result obj = db.ms_logictest_result.Find(id);
                        ms_logictest_result obj = new ms_logictest_result();
                        obj.fk_applicant_information_form = Convert.ToInt32(id);
                        var logictest_duration = Int32.Parse((db.ms_all_for_one.Where(x => x.pk_all_for_one == 1).FirstOrDefault()).var_value);
                        obj.end_time = DateTime.UtcNow.AddSeconds(logictest_duration);
                        
                        //var obj_pdf_problems = db.historical_invitation_progress.Where(x => x.fk_applicant_information_form == (long)obj.fk_applicant_information_form && x.access_token == active).FirstOrDefault();//ini buat ambil objek/baris di kolom histrocal_invitation yang page logic_test masih bisa diakses(access_token=1) oleh pengguna (fk_applicant_information_form)
                        obj.fk_logictest_problems = obj_pdf_problems.fk_logictest_problems;
                        db.ms_logictest_result.Add(obj);

                        //start of /make logictest user can only access StartAndRedirect action one time
                        obj_pdf_problems.logic_test_first_access=1;
                        db.Entry(obj_pdf_problems).State = EntityState.Modified;

                        //end of /make logictest user can only access StartAndRedirect action one time

                        //db.ms_employee.Remove(obj_ms_employee);

                        db.SaveChanges();
                        transaction.Commit();
                        var pk_id = obj.pk_logictest_result;
                        TempData["link"] = link;
                        return RedirectToAction("UploadZIP", new { pk_id2 = EncryptString(key, pk_id.ToString())  });
                    }
                    return View();
                }
                catch (Exception ex)
                {

                    transaction.Rollback();
                    Console.WriteLine(ex.Message);
                    return View();

                }
            }

        }

        [HttpGet]
        public ActionResult UploadZIP(string pk_id2, string FileDetails)
        {
            var key = "b14ca5898a4e4133bbce2ea2315a1916";
            var obj1 = pk_id2.Replace(" ", "+");
            var pk_id = Convert.ToInt64(DecryptString(key, obj1)); 
            ViewBag.link = TempData["link"];
            var obj = db.ms_logictest_result.Where(x => x.pk_logictest_result == (int)pk_id).FirstOrDefault();
            ViewBag.EndTime_LT = obj.end_time;

            var obj2 = db.ms_personal_data.Where(s => s.pk_employee == obj.fk_applicant_information_form).FirstOrDefault();
            ViewBag.Email = obj2.email;

            ViewBag.ID =EncryptString(key, obj.pk_logictest_result.ToString());

            ViewBag.FileDetails = FileDetails;

            return View();
        }

        [HttpPost]
        public ActionResult UploadZIP(HttpPostedFileBase file,string link,string email,string pk_id2)
        {
            using (DbContextTransaction transaction = db.Database.BeginTransaction())
            {
                try
                {
                    var key = "b14ca5898a4e4133bbce2ea2315a1916";
                    var obj1 = pk_id2.Replace(" ", "+");
                    var pk_id = Convert.ToInt64(DecryptString(key, obj1));
                    if (file.ContentLength > 0 && Path.GetExtension(file.FileName).ToUpper() == ".ZIP" && Path.GetFileName(file.FileName).Length < 105)
                    {
                        //ViewBag.EndTime = obj.end_time;
                        int fk_applicant = Convert.ToInt16((from s in db.ms_personal_data where s.email == email select s.pk_employee).FirstOrDefault());
                        string _FileName = Path.GetFileName(file.FileName);
                        string _path = Path.Combine(Server.MapPath("~/Uploaded_LogicTestSolutions"), _FileName);
                        //string _FileExt = ;
                        file.SaveAs(_path);
                        ViewBag.Message = "File Uploaded Successfully!!";
                        var obj_zip = db.ms_logictest_result.Where(x => x.pk_logictest_result == (int)pk_id).FirstOrDefault();
                        obj_zip.logictest_solutions = _FileName;
                        //obj_zip.fk_applicant_information_form = fk_applicant;
                        obj_zip.logictest_solutions_path = "~/Uploaded_LogicTestSolutions";
                        obj_zip.date_created = DateTime.Now;
                        obj_zip.date_test = DateTime.Now;
                        obj_zip.created_by = email;
                        //var obtest = db.historical_invitation_progress.Where(x => x.pk_historical_invitation_progress == (int)obj_zip.fk_applicant_information_form).FirstOrDefault
                        db.Entry(obj_zip).State = EntityState.Modified;
                        db.SaveChanges();
                        long pk_rekrut = (from s in db.ms_recruit where s.fk_applicant_information_form == fk_applicant select s.pk_recruitID).FirstOrDefault();
                        var query4 = db.ms_recruit.Find(pk_rekrut);
                        if (pk_rekrut != 0)
                        {
                            query4.data_crated = DateTime.Now;
                            query4.fk_logictest_result = obj_zip.pk_logictest_result;
                            db.Entry(query4).State = EntityState.Modified;
                        }
                        else
                        {
                            var x = new ms_recruit();
                            x.fk_logictest_result = obj_zip.pk_logictest_result;
                            x.data_crated = DateTime.Now;
                            db.ms_recruit.Add(x);
                        }
                        var logicdone = (from s in db.historical_invitation_progress where s.fk_applicant_information_form == fk_applicant && s.access_token == 1 select s).FirstOrDefault();
                        logicdone.logictest_status = 3;
                        db.Entry(logicdone).State = EntityState.Modified;
                        TempData["message"] = 1;
                        db.SaveChanges();
                        transaction.Commit();
                        TempData["message"] = 3;
                        var obj_link = db.historical_invitation_progress.Where(x => x.fk_applicant_information_form == fk_applicant && x.access_token == 1).FirstOrDefault();
                        var enc_link = obj_link.link;
                        return RedirectToAction("Index", "Recruitment", new { obj = enc_link });
                        
                        //return View();
                    }
                    else if (Path.GetFileName(file.FileName).Length >= 105)
                    {
                        ViewBag.FileDetails = "Filename is too long.";
                        var obj = db.ms_logictest_result.Where(x => x.pk_logictest_result == (int)pk_id).FirstOrDefault();
                        ViewBag.EndTime_LT = obj.end_time;

                        var obj2 = db.ms_personal_data.Where(s => s.pk_employee == obj.fk_applicant_information_form).FirstOrDefault();
                        ViewBag.Email = obj2.email;
                        TempData["link"] = link;
                        return RedirectToAction("UploadZIP", new { pk_id2 = EncryptString(key, pk_id.ToString()), FileDetails = ViewBag.FileDetails });
                    }
                    else 
                    {
                        ViewBag.FileDetails = "Invalid file format.";
                        var obj = db.ms_logictest_result.Where(x => x.pk_logictest_result == (int)pk_id).FirstOrDefault();
                        ViewBag.EndTime_LT = obj.end_time;

                        var obj2 = db.ms_personal_data.Where(s => s.pk_employee == obj.fk_applicant_information_form).FirstOrDefault();
                        ViewBag.Email = obj2.email;
                        TempData["link"] = link;

nawadaya_project/Views/StartLogicTest/UpdateZIP.cshtml
@model nawadaya_project.Models.ms_logictest_result
@{
    ViewBag.Title = "UpdateZIP";
}



<body>
    <div class="card">


        <div class="card-block">

            @using (Html.BeginForm("UploadZIP", "UploadLogicTestResult", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">

                    <div class="col-sm-10">
                        Upload solutions inside a file .zip <br />
                        @*<button class="btn btn-primary">Upload</button>*@
                        @Html.TextBox("file", "", new { type = "file" }) <br />
                        <button class="btn btn-primary">Upload</button>
                        @*<input type="submit" value="Upload" />*@
                        @ViewBag.Message
                    </div>
                </div>



            }


        </div>

    </div>



    <div class="pcoded-inner-content">
        <!-- Main-body start -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-body start -->
                <div class="page-body">
                    <!-- Master Employee card start -->
                    <button onclick="window.open('@Url.Action("openviewpdf", "UploadLogicTestResult")')" class="btn btn-primary">Open Problems</button>
                    @*<input type="button" value="Open" onclick="window.open('@Url.Action("openviewpdf", "UploadLogicTestResult")')" />*@
                </div>
                <!-- Page-body end -->
            </div>
        </div>
        <!-- Main-body end -->

        <div id="styleSelector">

        </div>
    </div>

</body>

nawadaya_project/Views/StartLogicTest/UploadZIP.cshtml
@*@model nawadaya_project.Models.ms_applicant_information_form*@
<!-- Masthead -->
@{
    
    if (@ViewBag.FileDetails != null)
    {
        <script>
            function codeAddress() {
                $("#modalfailedupload")
                    .closest(".modal").modal('show');
            }
            window.onload = codeAddress;
        </script>
    }
}

<div id="modalfailedupload" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel">Upload Failed</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p>@ViewBag.FileDetails</p>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn  btn-secondary" data-dismiss="modal">Ok</button>
                @*@Html.ActionLink("Select PDF", "SelectPDF", new { id = @item.pk_logictest_pdf_id }, new { @class = "btn btn-danger" })*@
            </div>
        </div>
    </div>
</div>

<header class="masthead">
    <div class="container h-100">
        <div class="container">
            @*<button onclick="window.open('@Url.Action("openviewpdf", "UploadLogicTestResult")')" class="btn btn-primary">Open Problems</button>*@
            <br><br>
                <textarea cols="10" disabled class="form-control" rows="8">
                GUIDE:

                Do this Logic Test Assessment by solving the problems as one bundling solutions.
                Use the php / java / vb.net / C# / ASP.Net / C++ / Pseudocode / javascript language.  
                You can view the problems by clicking OPEN PROBLEMS button.
                Submit all solutions as one .zip which containing 1 project / 1 solution that can be run as an application.
                Specifically for React Native project, please do not include the node_modules, android and ios folders in the .zip file.
                Upload a .zip file and click Save Changes to finish your Nawadata Logic Test.
            </textarea>
            <br>
            <div class="form-group">

                <div class="col-sm-12">
                    <button type="button" onclick="window.open('@Url.Action("viewpdfnewtab", "StartLogicTest", new { id2 = ViewBag.ID })')" class="btn btn-primary btn-xl">Open Problems</button>
                    @*<a href="@Url.Action("viewpdfnewtab","StartLogicTest", new { id = ViewBag.ID })" target="_blank">Open AAA Problems</a>*@
                </div>
            </div>
            @*<iframe src="~/pdf/ASP.NET_MVC_Untuk_Pemula_2016.pdf" width="100%" height="100%"></iframe>*@
            @using (Html.BeginForm("UploadZIP", "StartLogicTest", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @*@Html.AntiForgeryToken()*@

                <div class="form-group">

                    <div class="col-sm-3">
                        <label><font color="white"> Upload solutions inside a file .zip.</font></label>
                    </div>
                    <div class="col-sm-12">
                        <input type="hidden" name="link" value="@ViewBag.link">
                        <input type="hidden" name="email" value="@ViewBag.Email">
                        <input type="hidden" name="pk_id2" value="@ViewBag.ID">
                        @*<button class="btn btn-primary">Upload</button>*@
                        @Html.TextBox("file", "", new { type = "file",accept = "application/zip", required = "required", @class = "form-control" }) <br />
                        @*<button type="button" class="btn btn-primary btn-xl" data-toggle="modal" data-target="#Modalalert">Save Changes</button>*@
                        @*<input type="submit" value="Upload" />*@
                        @*@ViewBag.Message*@
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modalalert">Save Changes</button>

                    </div>
                </div>
                <div class="form-group">

                    <div class="col-sm-12">

                    </div>
                </div>
                <div class="modal fade" id="Modalalert" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Save Changes</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Double-check your file submission if there is still enough time left before saving changes.<br><br>
                                You can only saving changes once. Are you sure to proceed?
                            </div>
                            <div class="modal-footer">
                                <div class="form-group">
                                    <input type="submit" name="submit" value="Save" class="btn btn-secondary" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                


            }


        </div>

        
        @*<div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Logic test</h1>
                <hr class="divider my-4">
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 font-weight-light mb-5">Nawa Data Logic Test</p>
                <button type="button" class="btn btn-primary btn-xl" data-toggle="modal" data-target="#exampleModalScrollable">
                    Start
                </button>
            </div>
        </div>*@
        @*<br><br>
        <h2 class="text-center mt-0">Logic Test</h2>
        <hr class="divider my-4">
        <br>*@
    </div>
</header>

nawadaya_project/Views/StartLogicTest/viewpdfnewtab.cshtml
@{
    ViewBag.Title = "openviewpdf";
    string pdf = ViewBag.PDF.Substring(1);
    var app_path = Url.Content("~/");
    var URL = app_path + pdf;
}



    <header class="masthead" style="height:1200px">
        <div class="container">

            <div class="embed-responsive embed-responsive-1by1">
                <iframe id="frame" class=" embed-responsive-item" src="@URL"></iframe>
                @*<iframe class=" embed-responsive-item" src="~/UploadedLogicTestProblemsPDF/Nawadata Logic Test Programmer.pdf"></iframe>*@
                @*<iframe src="~/pdf/ASP.NET_MVC_Untuk_Pemula_2016.pdf" width="100%" height="100%"></iframe>*@
                @*<iframe class="embed-responsive-item" src="~/UploadedLogicTestProblemsPDF/ASP.NET_MVC_Untuk_Pemula_2016.pdf"></iframe>*@
            </div>

        </div>

    </header>
    <style>
        

        #frame {
            zoom: 0.75;
            
        }
    </style>