nawadaya_project/Models/ms_skill.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nawadaya_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_skill
    {
        public long pk_keterampilan_dalam_bidang { get; set; }
        public Nullable<int> fk_applicant_information_form { get; set; }
        public string nama { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
    }
}

nawadaya_project/Models/ms_status.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nawadaya_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_status
    {
        public long pk_statusID { get; set; }
        public string employee_status_name { get; set; }
    }
}

nawadaya_project/Controllers/RMController.cs
using nawadaya_project.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;


namespace project_nawadaya.Controllers
{
    public class RMController : Controller
    {
        // GET: RM
        public ActionResult Index()
        {
            if (Session["UserName"] == null)
            {
                if (Session["UserName"] == null)
                {
                    return RedirectToAction("Index", "Login");
                }
            }
            var data3 = (from s in db.logins select s).ToList();
            var listuser = db.tbl_user.ToList();
            int countinguser = 0;
            foreach (var item in listuser) {
                countinguser++;
            }
            var listemployee = db.ms_personal_data.Where(x =>x.status_employee==3).ToList();
            int countingemployee = 0;
            foreach (var item in listemployee)
            {
                countingemployee++;
            }
            ViewBag.countuser = countinguser;
            ViewBag.countemployee = countingemployee;

            ViewBag.datalogin = data3;

            return View();
        }

        private Nawadaya_Entities db = new Nawadaya_Entities();
        //public ActionResult MsSkill()
        //{

        //    if (Session["UserName"] == null)
        //    {
        //        return RedirectToAction("Index", "Login");
        //    }
        //    else
        //    {
        //        var data = (from s in db.ms_skill select s).ToList();
        //        ViewBag.AddSkill = data;
        //    }

        //    return View();
        //}

        //[HttpPost]
        //public ActionResult AddSkill(ms_skill _post)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _post.created_by = Session["UserName"].ToString();
        //        _post.data_crated = DateTime.Now;
        //        db.ms_skill.Add(_post);
        //        db.SaveChanges();
        //        return RedirectToAction("MsSkill");

        //        //return Json(_post);
        //    }
        //    TempData["message"] = 0;
        //    return View();
        //}

        //[HttpGet]
        //public ActionResult DeleteSkill(int id)
        //{
        //    var query = db.ms_skill.Where(s => s.pk_skill == id).First();
        //    db.ms_skill.Remove(query);
        //    db.SaveChanges();
        //    return RedirectToAction("MsSkill");
        //}

        //public ActionResult EditSkill(int id)
        //{
        //    var query = db.ms_skill.Where(s => s.pk_skill == id).First();
        //    ViewBag.EditSkill = query;
        //    var data = (from s in db.ms_skill select s).ToList();
        //    ViewBag.AddSkill = data;
        //    ViewBag.PKskill = id;
        //    return View("MsSkill", query);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult EditSkill(ms_skill item)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        var data = db.ms_skill.Find(item.pk_skill);
        //        data.skill_name = item.skill_name;
        //        data.created_by = Session["UserName"].ToString();
        //        data.data_crated = DateTime.Now;
        //        db.Entry(data).State = EntityState.Modified;
        //        db.SaveChanges();
        //        // return Json(_post);
        //        return RedirectToAction("MsSkill");
        //    }

        //    return View();
        //}

        //public ActionResult MsRole()
        //{

        //    if (Session["UserName"] == null)
        //    {
        //        return RedirectToAction("Index", "Login");
        //    }
        //    else
        //    {
        //        var data = (from s in db.ms_role select s).ToList();
        //        ViewBag.MsRole = data;
        //    }

        //    return View();
        //}

        //public ActionResult MsStatus()
        //{

        //    if (Session["UserName"] == null)
        //    {
        //        return RedirectToAction("Index", "Login");
        //    }
        //    else
        //    {
        //        var data = (from s in db.ms_status select s).ToList();
        //        ViewBag.MsStatus = data;
        //    }

        //    return View();
        //}

        //[HttpPost]
        //public ActionResult AddStatus(ms_status _post)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _post.created_by = Session["UserName"].ToString();
        //        _post.data_crated = DateTime.Now;
        //        db.ms_status.Add(_post);
        //        db.SaveChanges();
        //        return RedirectToAction("MsStatus");

        //        //return Json(_post);
        //    }
        //    TempData["message"] = 0;
        //    return View();
        //}

        //[HttpGet]
        //public ActionResult DeleteStatus(int id)
        //{
        //    var query = db.ms_status.Where(s => s.pk_statusID == id).First();
        //    db.ms_status.Remove(query);
        //    db.SaveChanges();
        //    return RedirectToAction("MsStatus");
        //}

        //public ActionResult EditStatus(int id)
        //{
        //    var query = db.ms_status.Where(s => s.pk_statusID == id).First();
        //    ViewBag.EditSkill = query;
        //    var data = (from s in db.ms_status select s).ToList();
        //    ViewBag.MsStatus = data;
        //    ViewBag.PKskill = id;
        //    return View("MsStatus", query);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult EditStatus(ms_status item)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        var data = db.ms_status.Find(item.pk_statusID);
        //        data.employee_status_name = item.employee_status_name;
        //        data.created_by = Session["UserName"].ToString();
        //        data.data_crated = DateTime.Now;
        //        db.Entry(data).State = EntityState.Modified;
        //        db.SaveChanges();
        //        // return Json(_post);
        //        return RedirectToAction("MsStatus");
        //    }

        //    return View();
        //}

        public ActionResult AddUser()
        {

            if (Session["UserName"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                var max = db.tbl_user.Max(r => r.pk_userID);
                var data2 = (from s in db.employee_adduser select s).ToList();
                var data3 = (from s in db.logins where s.role_name != "Super Admin" select s).ToList();
                var data4 = (from s in db.ms_role select s).ToList();
                ViewBag.DataKaryawan = data2;
                ViewBag.datalogin = data3;
                ViewBag.datarole = data4;
                //ViewBag.MaxID = max;
                ViewBag.message = TempData["message"];
                //start/viewbag untuk modal updaterole/KMS 
                ViewBag.update_role_message = TempData["update_role_message"];
                //end/viewbag untuk modal updaterole/KMS 
            }

            return View();
        }

        [HttpPost]
        public ActionResult AddUser(tbl_user post,string email,int role)
        {
            using (DbContextTransaction transaction = db.Database.BeginTransaction())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        var key = "b14ca5898a4e4133bbce2ea2315a1916";
                        var password = md5(post.password);
                        var link = EncryptString(key, string.Format("{0}", email));
                        var new_role = (db.ms_role.Where(x => x.pk_role == role).FirstOrDefault()).role_name;
                        var validation = SendEmail(email, link, new_role);
                        if (validation == true)
                        {
                            post.password = password;
                            post.fk_role = role;
                            post.created_by = Session["UserName"].ToString();
                            post.data_crated = DateTime.Now;
                            db.tbl_user.Add(post);
                            db.SaveChanges();
                            transaction.Commit();
                            TempData["message"] = 1;
                        }
                        else
                        {
                            TempData["message"] = 0;
                        }
                        return RedirectToAction("AddUser");

                        //return Json(_post);
                    }
                    ViewBag.message = 1;
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    transaction.Rollback();
                }
            }
            
            return View();

        }

        public static string EncryptString(string key, string plainInput)
        {
            byte[] iv = new byte[16];
            byte[] array;
            using (Aes aes = Aes.Create())
            {
                aes.Key = Encoding.UTF8.GetBytes(key);
                aes.IV = iv;
                ICryptoTransform encryptor = aes.CreateEncryptor(aes.Key, aes.IV);
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    using (CryptoStream cryptoStream = new CryptoStream((Stream)memoryStream, encryptor, CryptoStreamMode.Write))
                    {
                        using (StreamWriter streamWriter = new StreamWriter((Stream)cryptoStream))
                        {
                            streamWriter.Write(plainInput);
                        }

nawadaya_project/Views/RM/AddEmployee.cshtml
@model nawadaya_project.Models.ms_personal_data

@{
    if (@ViewBag.message != null)
    {
        <script>
            function codeAddress() {
                $("#message")
                    .closest(".modal").modal('show');
            }
            window.onload = codeAddress;
        </script>
    }
}
<aside>
    <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">
            <div style="color:white">
                <h4 class="centered">
                    @if (@Session["FullName"] != null)
                    {
                        @Session["FullName"];
                    }
                </h4>
                <h6 class="centered">
                    @if (@Session["Email"] != null)
                    {
                        @Session["Email"];
                    }
                </h6>
            </div>
            <li class="mt">
                <a href="@Url.Action("Index","RM")">
                    <i class="fa fa-dashboard"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="sub-menu">
                <a class="active" href="javascript:;">
                    <i class="fa fa-cogs"></i>
                    <span>User Management</span>
                </a>
                <ul class="sub">
                    <li class="active"><a href="@Url.Action("AddEmployee","RM")">Master Employee</a></li>
                    <li><a href="@Url.Action("AddUser","RM")">Master User</a></li>
                </ul>
            </li>
            @*<li class="sub-menu">
                <a href="javascript:;">
                    <i class="fa fa-book"></i>
                    <span>Historical User Assignment</span>
                </a>
            </li>*@
            @*<li class="sub-menu">
                <a class="active">
                    <i class="fa fa-book"></i>
                    <span>Master Data</span>
                </a>
                <ul class="sub">

                    @*<li><a href="@Url.Action("MsSkill","RM")">Master Skill</a></li>
                    <li><a href="@Url.Action("MsStatus","RM")">Master Status</a></li>*@
            @*</ul>
                    </li>
                </ul>*@
            <!-- sidebar menu end-->
    </div>
</aside>
<!-- Main-->
<section id="main-content">
    <section class="wrapper site-min-height">
        <h3>Master Employee</h3>
        <div class="card-header">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ModalAddEmployee">
                Add Employee
            </button>
        </div>
        <div class="row mt">
            <div class="col-lg-12">
                <table id="example2" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>NIP</th>
                            <th>Name</th>
                            <th>Position</th>
                            <th>ACTIONS</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                            if (ViewBag.MsEmployee != null)
                            {
                                foreach (var item in ViewBag.MsEmployee)
                                {
                                    <tr>
                                        <td>@i</td>
                                        <td>@item.NIP</td>
                                        <td>@item.full_name</td>
                                        <td>@item.position</td>
                                        <td>
                                            <a href="@Url.Action("DetailEmployee", "RM", new { id = item.pk_employee })" class="btn btn-info">
                                                Details
                                            </a>
                                            <a href="@Url.Action("DeleteEmployee", "RM", new { id = item.pk_employee })" class="btn btn-danger">
                                                Delete
                                            </a>

                                        </td>
                                    </tr>
                                    i++;
                                }
                            }
                        }
                </table>
                <!-- /Message Panel-->
            </div>

        </div>
    </section>
    <!-- /wrapper -->
</section>

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="message" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Master Employee</h4>
            </div>
            <div class="modal-body">
                @if (ViewBag.message != null)
                {
                    if (ViewBag.message == 0)
                    {
                        <div class="alert alert-danger"><b>Failed!</b> Employee is not added.</div>
                    }
                    else if (ViewBag.message == 1)
                    {
                        <div class="alert alert-success"><b>Success!</b> Employee is added.</div>
                    }
                    else if (ViewBag.message == 2)
                    {
                        <div class="alert alert-danger"><b>Failed!</b> Email is already exist.</div>
                    }
                    else
                    {
                        <div class="alert alert-success"><b>Success!</b> Employee is deleted.</div>
                    }
                }
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
            </div>
        </div>
    </div>
</div>


<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="ModalAddEmployee" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Add New Employee</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("AddEmployee", "RM", FormMethod.Post))
                {
                    <label>Full Name :</label><br>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.full_name, new { @type = "text", required = "required", placeholder = "Fullname Employee", @class = "form-control" })
                    </div>
                    <label>Nick Name :</label><br>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.name_called, new { @type = "text", required = "required", placeholder = "Nickname Employee", @class = "form-control" })
                    </div>
                    <label>Position :</label><br>
                    <div class="form-group">
                        <select name="position" required class="form-control">
                            <option value="">Select Position</option>
                            <option value="Developer">Developer</option>
                            <option value="Technical Leader">Technical Leader</option>
                            <option value="Project Manager">Project Manager</option>
                            <option value="Quality Assurance">Quality Assurance</option>
                            <option value="Finance">Finance</option>
                            <option value="Administration">Administration</option>
                            <option value="Human Resources">Human Resources</option>
                            <option value="C Level">C Level</option>
                        </select>
                    </div>
                    <label>Email :</label><br>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.email, new { @type = "email", required = "required", placeholder = "Input Email Employee", @class = "form-control" })
                    </div>
                    <div class="modal-footer">
                        <div class="form-group">
                            <input type="submit" name="submit" value="Submit" class="btn btn-success" />
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>

</div>

nawadaya_project/Views/RM/Index.cshtml
<aside>
    <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">
            <div style="color:white">
                <h4 class="centered">
                    @if (@Session["FullName"] != null)
                    {
                        @Session["FullName"];
                    }
                </h4>
                <h6 class="centered">
                    @if (@Session["Email"] != null)
                    {
                        @Session["Email"];
                    }
                </h6>
            </div>
            <li class="mt">
                <a class="active" href="@Url.Action("Index","RM")">
                    <i class="fa fa-dashboard"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="sub-menu">
                <a href="javascript:;">
                    <i class="fa fa-cogs"></i>
                    <span>User Management</span>
                </a>
                <ul class="sub">
                    <li><a href="@Url.Action("AddEmployee","RM")">Master Employee</a></li>
                    <li><a href="@Url.Action("AddUser","RM")">Master User</a></li>
                </ul>
            </li>
            @*<li class="sub-menu">
                <a href="javascript:;">
                    <i class="fa fa-book"></i>
                    <span>Historical User Assignment</span>
                </a>
            </li>*@
            @*<li class="sub-menu">
                <a class="active">
                    <i class="fa fa-book"></i>
                    <span>Master Data</span>
                </a>
                <ul class="sub">

                    @*<li><a href="@Url.Action("MsSkill","RM")">Master Skill</a></li>
                    <li><a href="@Url.Action("MsStatus","RM")">Master Status</a></li>*@
                @*</ul>
            </li>
        </ul>*@
        <!-- sidebar menu end-->
    </div>
</aside>

<section id="main-content">
    <section class="wrapper site-min-height">
        <h3>Dashboard</h3>
        <div class="row mt">
            <div class="col-sm-6">
                <!-- REVENUE PANEL -->
                <div style="height:150px;background-color:white" class="green-panel pn">
                    <div class="green-header">
                        <h5>Users</h5>
                    </div>
                    <font size="72">@ViewBag.countuser</font>
                </div>
            </div>
            <div class="col-sm-6">
                <!-- REVENUE PANEL -->
                <div style="height:150px;background-color:white" class="green-panel pn">
                    <div class="green-header">
                        <h5>Employee</h5>
                    </div>
                    <font size="72">@ViewBag.countemployee</font>
                </div>
            </div>

                <div style="margin-top:30px" class="col-lg-12">
                    <table id="example2" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Username</th>
                                <th>Hak Akses</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 1;
                            }
                            @foreach (var item in ViewBag.datalogin)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@item.full_name</td>
                                    <td>@item.email</td>
                                    <td>@item.username</td>
                                    @if (@item.role_name == "Super Admin")
                                    {
                                        <td><span class="label label-primary">@item.role_name</span></td>
                                    }
                                    else if (@item.role_name == "Admin")
                                    {
                                        <td><span class="label label-warning">@item.role_name</span></td>
                                    }
                                    else
                                    {
                                        <td><span class="label label-danger">@item.role_name</span></td>
                                    }
                                </tr>
                                i++;
                            }
                    </table>
                    <!-- /Message Panel-->
                </div> 
        </div>
    </section>
    <!-- /wrapper -->
</section>

<script type="text/javascript">

    function preventBack() { window.history.forward(); }
    setTimeout("preventBack()", 0);
    window.onunload = function () { null };

</script>

nawadaya_project/Views/RM/MsSkill.cshtml
@model nawadaya_project.Models.ms_skill

@{
    if (@ViewBag.PKskill != null)
    {
        <script>
        function codeAddress() {
            $("#modal-update")
            .closest(".modal").modal('show');
        }
        window.onload = codeAddress;
        </script>
    }
}

<aside>
    <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">
            <p class="centered"><a href="profile.html"><img src="~/Content/img/ui-sam.jpg" class="img-circle" width="80"></a></p>
            <h5 class="centered">Sam Soffes</h5>
            <li class="mt">
                <a href="@Url.Action("Index","RM")">
                    <i class="fa fa-dashboard"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="sub-menu">
                <a href="javascript:;">
                    <i class="fa fa-cogs"></i>
                    <span>Process</span>
                </a>
                <ul class="sub">
                    <li><a href="@Url.Action("AddUser","RM")">Add User</a></li>
                </ul>
            </li>
            <li class="sub-menu">
                <a class="active" href="javascript:;">
                    <i class="fa fa-book"></i>
                    <span>Master Data</span>
                </a>
                <ul class="sub">
                    <li><a href="@Url.Action("MsRole","RM")">Master Role</a></li>
                    <li class="active"><a href="@Url.Action("MsSkill","RM")">Master Skill</a></li>
                </ul>
            </li>
        </ul>
        <!-- sidebar menu end-->
    </div>
</aside>

<section id="main-content">
    <section class="wrapper site-min-height">
        <h3>Master Skill</h3>
        <div class="card-header">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ModalAddSkill">
                Add Skill
            </button>
        </div>
        <div class="row mt">
            <div class="col-lg-12">
                <table id="example2" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>ACTIONS</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                        }
                        @foreach (var item in ViewBag.AddSkill)
                        {
                            <tr>
                                <td>@i</td>
                                <td>@item.skill_name</td>
                                <td>
                                    <a href="@Url.Action("EditSkill", "RM",new {id=item.pk_skill})" class="btn btn-warning">
                                        Update
                                    </a>
                                    <a href="@Url.Action("DeleteSkill", "RM",new {id=item.pk_skill})" class="btn btn-danger">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                            i++;
                        }
                </table>

                <!-- /Message Panel-->
            </div>

        </div>
    </section>
    <!-- /wrapper -->
</section>

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="ModalAddSkill" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Add Master Skill</h4>
            </div>
            @using (Html.BeginForm("AddSkill", "RM", FormMethod.Post))
            {
                <div class="modal-body">
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.nama, new { @type = "text", @placeholder = "Input name skill", @class = "form-control" })
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <input type="submit" name="submit" value="Add Post" class="btn btn-success" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="modal-update" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Update Master Skill</h4>
            </div>
            @using (Html.BeginForm("EditSkill", "RM", FormMethod.Post))
            {
                <div class="modal-body">
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(s => s.pk_keterampilan_dalam_bidang)
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.nama, new { @type = "text", @placeholder = "Input name skill", @class = "form-control" })
                    </div>
                </div>
                    <div class="modal-footer">
                        <div class="form-group">
                            <input type="submit" name="submit" value="Add Post" class="btn btn-success" />
                        </div>
                    </div>
            }
        </div>
    </div>
</div>