nawadaya_project/Controllers/RecruitmentController.cs
using nawadaya_project.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace project_nawadaya.Controllers
{
    public class RecruitmentController : Controller
    {

        public ActionResult StartDISC(string obj)
        {
            var query = db.historical_invitation_progress.Where(x=>x.link == obj && x.access_token==1).FirstOrDefault();
            var DISCduration = Convert.ToInt32((db.ms_all_for_one.Where(x => x.pk_all_for_one == 3).FirstOrDefault()).var_value);
            query.endtime = Convert.ToDateTime(DateTime.UtcNow.AddSeconds(DISCduration));
            db.Entry(query).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Disc", new { obj = obj });
        }
        // GET: Recruitment
        public ActionResult Disc(string obj)
        {
            var obj1 = "";
            if (obj != null)
            {
                obj1 = obj.Replace(" ", "+");
            }
            var linkactive = (from s in db.historical_invitation_progress where s.link == obj1 && s.access_token == 1 select s).FirstOrDefault();
            var duration = db.historical_invitation_progress.Where(x => x.link == obj1 && x.access_token==1).FirstOrDefault();
            if (duration.endtime != null)
            {
                ViewBag.TimeDisc = 1;
                ViewBag.EndTime_LT = duration.endtime;
            }
            if (linkactive != null)
            {
                var key = "b14ca5898a4e4133bbce2ea2315a1916";
                var data = DecryptString(key, obj1);
                string[] separate = data.Split('=','&');
                ViewBag.Email = separate[3];
                ViewBag.Link = obj1;
                var email = separate[3];
                var query = (from s in db.ms_personal_data where s.email == email select s).FirstOrDefault();
                var query2 = (from s in db.ms_problem_disc where s.active==1 select s).ToList();
                ViewBag.DISC = query2;
                return View();
            }
            else
            {
                return RedirectToAction("NotFound", "OtherPage");
            }
        }

        public ActionResult CountDISC(string result, string email)
        {

            var pk = (from s in db.ms_personal_data where s.email.Equals(email) select s.pk_employee).FirstOrDefault();
            var link = (from s in db.historical_invitation_progress where s.fk_applicant_information_form == pk && s.access_token == 1 select s.link).FirstOrDefault();
            link = link.Replace(" ", "+");
            using (DbContextTransaction transaction = db.Database.BeginTransaction())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        var Emailexist = (from s in db.ms_personal_data where s.email.Equals(email) select s).ToList();
                        if (Emailexist.Count > 1)
                        {
                            TempData["message"] = 2;
                            return RedirectToAction("Form", new { obj = link });
                        }
                        else
                        {
                            string[] disc = result.Split(',');
                            
                                var data = new ms_disc_result();
                                data.fk_applicant_information_form = Convert.ToInt16(pk);
                                data.MD = Convert.ToInt16(disc[0]);
                                data.MI = Convert.ToInt16(disc[1]);
                                data.MS = Convert.ToInt16(disc[2]);
                                data.MC = Convert.ToInt16(disc[3]);
                                data.LD = Convert.ToInt16(disc[4]);
                                data.LI = Convert.ToInt16(disc[5]);
                                data.LS = Convert.ToInt16(disc[6]);
                                data.LC = Convert.ToInt16(disc[7]);
                                data.xM = Convert.ToInt16(disc[8]);
                                data.xL = Convert.ToInt16(disc[9]);
                                data.AD = data.MD - data.LD;
                                data.AI = data.MI - data.LI;
                                data.AS = data.MS - data.LS;
                                data.AC = data.MC - data.LC;
                                data.Total_M = data.MD + data.MI + data.MS + data.MC + data.xM;
                                data.Total_L = data.LD + data.LI + data.LS + data.LC + data.xL;
                                data.created_by = email;
                                data.date_created = DateTime.Now;
                                db.ms_disc_result.Add(data);
                                db.SaveChanges();
                                var pk_disc_id = data.pk_disc_result;
                                //tambahan baru disc//start
                                ms_disc_graph_result obj_graph_res = new ms_disc_graph_result();
                                var obj_result = db.ms_disc_result.Where(x => x.pk_disc_result == pk_disc_id).FirstOrDefault();
                                obj_graph_res.fk_disc_result = obj_result.pk_disc_result;

                                //Most
                                var obj_GMD = db.ms_graphvalue_mostleast.Where(x => x.tablevalue == (int)obj_result.MD).FirstOrDefault();
                                obj_graph_res.RGMD = obj_GMD.GMD;

                                var obj_GMI = db.ms_graphvalue_mostleast.Where(x => x.tablevalue == (int)obj_result.MI).FirstOrDefault();
                                obj_graph_res.RGMI = obj_GMI.GMI;

                                var obj_GMS = db.ms_graphvalue_mostleast.Where(x => x.tablevalue == (int)obj_result.MS).FirstOrDefault();
                                obj_graph_res.RGMS = obj_GMS.GMS;

                                var obj_GMC = db.ms_graphvalue_mostleast.Where(x => x.tablevalue == (int)obj_result.MC).FirstOrDefault();
                                obj_graph_res.RGMC = obj_GMC.GMC;
                                //

                                //Least
                                var obj_GLD = db.ms_graphvalue_mostleast.Where(x => x.tablevalue == (int)obj_result.LD).FirstOrDefault();
                                obj_graph_res.RGLD = obj_GLD.GLD;

                                var obj_GLI = db.ms_graphvalue_mostleast.Where(x => x.tablevalue == (int)obj_result.LI).FirstOrDefault();
                                obj_graph_res.RGLI = obj_GLI.GLI;

                                var obj_GLS = db.ms_graphvalue_mostleast.Where(x => x.tablevalue == (int)obj_result.LS).FirstOrDefault();
                                obj_graph_res.RGLS = obj_GLS.GLS;

                                var obj_GLC = db.ms_graphvalue_mostleast.Where(x => x.tablevalue == (int)obj_result.LC).FirstOrDefault();
                                obj_graph_res.RGLC = obj_GLC.GLC;
                                //

                                //Change (M-L)=A
                                var obj_GAD = db.ms_graphvalue_change.Where(x => x.tablevalue == (int)obj_result.AD).FirstOrDefault();
                                obj_graph_res.RGAD = obj_GAD.GAD;

                                var obj_GAI = db.ms_graphvalue_change.Where(x => x.tablevalue == (int)obj_result.AI).FirstOrDefault();
                                obj_graph_res.RGAI = obj_GAI.GAI;

                                var obj_GAS = db.ms_graphvalue_change.Where(x => x.tablevalue == (int)obj_result.AS).FirstOrDefault();
                                obj_graph_res.RGAS = obj_GAS.GAS;

                                var obj_GAC = db.ms_graphvalue_change.Where(x => x.tablevalue == (int)obj_result.AC).FirstOrDefault();
                                obj_graph_res.RGAC = obj_GAC.GAC;

                                db.ms_disc_graph_result.Add(obj_graph_res);
                                db.SaveChanges();


                                var pk_graph_to_descr = obj_graph_res.pk_disc_graph_result;
                                //
                                ms_DISC_final_result obj_DISC_final = new ms_DISC_final_result();
                                var obj_graph = db.ms_disc_graph_result.Where(x => x.pk_disc_graph_result == pk_graph_to_descr).FirstOrDefault();
                                obj_DISC_final.fk_disc_graph_result = obj_graph.pk_disc_graph_result;

                                var mostnum = countDISC((double)obj_graph.RGMD, (double)obj_graph.RGMI, (double)obj_graph.RGMS, (double)obj_graph.RGMC);
                                var leastnum = countDISC((double)obj_graph.RGLD, (double)obj_graph.RGLI, (double)obj_graph.RGLS, (double)obj_graph.RGLC);
                                var changenum = countDISC((double)obj_graph.RGAD, (double)obj_graph.RGAI, (double)obj_graph.RGAS, (double)obj_graph.RGAC);

                                var obj_chars_most = db.ms_DISC_personal_characters.Where(x => x.pk_DISC_personal_characters == (long)mostnum).FirstOrDefault();
                                var obj_chars_least = db.ms_DISC_personal_characters.Where(x => x.pk_DISC_personal_characters == (long)leastnum).FirstOrDefault();
                                var obj_chars_change = db.ms_DISC_personal_characters.Where(x => x.pk_DISC_personal_characters == (long)changenum).FirstOrDefault();

                                var obj_descr_change = db.ms_DISC_personal_description.Where(x => x.pk_DISC_personal_description == (long)changenum).FirstOrDefault();
                                var obj_jobsmatch_change = db.ms_DISC_jobs_match.Where(x => x.pk_DISC_jobs_match == (long)changenum).FirstOrDefault();

                                obj_DISC_final.mostA = obj_chars_most.a;

nawadaya_project/Views/Recruitment/Index.cshtml
@{
    if (ViewBag.message != null)
    {
        <script>
            function codeAddress() {
                $("#message")
                    .closest(".modal").modal('show');
            }
            window.onload = codeAddress;
        </script>
    }

    int progress = ViewBag.progress;
    int banyak = ViewBag.Banyak;
    int panjang = 100 / banyak;
    int bar = panjang * progress;


    if (bar == 100)
    {
        <script>
            function codeAddress() {
                $("#thanku").css("display", "block");
                $("#headerindex").css("display", "none");
                $("#form").css("display", "none");
            }
            window.onload = codeAddress;
        </script>
    }
}


<header class="masthead" id="thanku" style="display:none">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Hi, @ViewBag.Fullname</h1>
                <hr class="divider my-4">
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 font-weight-light mb-5">You has been completed these assessments. Thanks for your participation.<br>We will contact you soon. </p>
            </div>
        </div>
    </div>
</header>
<!-- Masthead -->
<header class="masthead" id="headerindex" style="display:block">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Welcome, @ViewBag.Fullname</h1>
                <hr class="divider my-4">
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 font-weight-light mb-5">
                    You will take Nawa Data pre-employment recruiting assessment.
                    Click CONTINUE to proceed.
                </p>
                <a class="btn btn-primary btn-xl js-scroll-trigger" href="#form">Continue</a>
            </div>
        </div>
        <br>
        <h2 class="text-center mt-0">Tests Menu</h2>
        <hr class="divider my-4">
    </div>
</header>

<!-- Services Section -->
<!-- Services Section -->
<section class="page-section" id="form" style="display:block">
    <div class="container">
        <div class="progress">
            <div class="progress-bar progress-bar-striped bg-danger progress-bar-animated" role="progressbar" aria-valuenow="@bar.ToString()" aria-valuemin="0" aria-valuemax="100" style="width:@bar.ToString()%;"></div>
        </div>
        <div class="row">
            @if (ViewBag.Problem != null)
            {
                int a = 1;
                foreach (string item in ViewBag.Problem)
                {
                    string name = item;
                    string[] index = name.Split('/');
                    var link = item + "?obj=" + ViewBag.Link;
                    if (ViewBag.Form == null)
                    {
                        if (a == 1)
                        {
                            a = 2;
                            <div class="col-3">
                                <p align="center">
                                <a class="nav-link" href="@link">
                                    @index[index.Length - 1]
                                    <i cls="fas fa-check text-dark"></i>
                                </a>
                                    </p>
                            </div>

                        }
                        else
                        {
                            <div class="col-3">

                                <p class="nav-link" align="center">
                                    @index[index.Length - 1]
                                    <i cls="fas fa-check text-dark"></i>
                                </p>
                            </div>

                        }
                    }
                    else
                    {
                        if (a == 1)
                        {
                            if (ViewBag.status == 1)
                            {
                                <div class="col-3">
                                    <p class="nav-link" align="center">
                                        @index[index.Length - 1]
                                        <i cls="fas fa-check text-dark"></i>
                                    </p>
                                </div>

                            }
                            a = 2;
                        }
                        else
                        {
                            if (index[index.Length - 1] == "Disc")
                            {
                                if (ViewBag.DISC != null)
                                {
                                    <div class="col-3">
                                        <p class="nav-link" align="center">
                                            DISC test@*@index[index.Length - 1]*@
                                            <i cls="fas fa-check text-dark"></i>
                                        </p>
                                    </div>

                                }
                                else
                                {
                                    <div class="col-3">
                                        <p align="center">
                                            <a class="nav-link" href="@link">
                                                DISC test@*@index[index.Length - 1]*@
                                                <i cls="fas fa-check text-dark"></i>
                                            </a>
                                            </p>
                                    </div>

                                }
                            }
                            else if (index[index.Length - 1] == "Psikotes")
                            {
                                if (ViewBag.psikotes != null)
                                {
                                    <div class="col-3">
                                        <p class="nav-link" align="center">
                                            Psychotest@*@index[index.Length - 1]*@
                                            <i cls="fas fa-check text-dark"></i>
                                        </p>
                                    </div>

                                }
                                else
                                {
                                    <div class="col-3">
                                        <p align="center">
                                            <a class="nav-link" href="@link">
                                                Psychotest@*@index[index.Length - 1]*@
                                                <i cls="fas fa-check text-dark"></i>
                                            </a>
                                            </p>
                                    </div>

                                }
                            }
                            else if (index[index.Length - 1] == "TestLogic")
                            {
                                if (ViewBag.logictest != null)
                                {
                                    <div class="col-3">
                                        <p class="nav-link" align="center">
                                            Logic Test@*@index[index.Length - 1]*@
                                            <i cls="fas fa-check text-dark"></i>
                                        </p>
                                    </div>

                                }
                                else
                                {
                                    <div class="col-3">
                                        <p align="center">
                                            <a class="nav-link" href="@link">
                                                Logic Test@*@index[index.Length - 1]*@
                                                <i cls="fas fa-check text-dark"></i>
                                            </a>
                                            </p>
                                    </div>

                                }
                            }


                        }
                    }

                }
            }


        </div>
    </div>
    <br><br><br>
</section>

<div class="modal fade" id="message" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Success!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @if (ViewBag.message != null)
                {
                    if (ViewBag.message == 0)
                    {
                        @*<div class="alert alert-danger"><b>Failed!</b> Add is failed</div>*@
                    }
                    else if (ViewBag.message == 1)
                    {
                        @*<div class="alert alert-success"><b>Success!</b> Your employment application forms is submitted.</div>*@
                        <div class="alert alert-success">Your employment application forms is submitted.</div>

                    }
                    else if (ViewBag.message == 3)
                    {
                        @*<div class="alert alert-success"><b>Success!</b> Your logic test solutions is submitted.</div>*@
                        <div class="alert alert-success">Your logic test solutions is submitted.</div>
                    }
                    else if (ViewBag.message == 4)
                    {
                        @*<div class="alert alert-success"><b>Success!</b> Your psychotest submission has been saved.</div>*@
                        <div class="alert alert-success">Your psychotest submission has been saved.</div>
                    }
                    else if (ViewBag.message == 2)
                    {
                        @*<div class="alert alert-success"><b>Success!</b> Your DISC test submission has been saved.</div>*@
                        <div class="alert alert-success">Your DISC test submission has been saved.</div>
                    }
                    else
                    {
                        @*<div class="alert alert-danger"><b>Success!</b> Delete is successfull!</div>*@
                    }
                }
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

nawadaya_project/Views/Recruitment/TestLogic.cshtml
@model nawadaya_project.Models.ms_personal_data
<!-- Masthead -->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Logic test</h1>
                <hr class="divider my-4">
            </div>
            <div class="col-lg-8 align-self-baseline">
                <button type="button" class="btn btn-primary btn-xl" data-toggle="modal" data-target="#exampleModalScrollable">
                    Start
                </button>
            </div>
        </div>
    </div>
</header>

<!-- Services Section -->
<!-- Services Section -->
@*<section class="page-section" id="form">
        <div class="container">
           <iframe src="~/pdf/ASP.NET_MVC_Untuk_Pemula_2016.pdf" width="100%" height="100%"></iframe>
            @using (Html.BeginForm("UploadLogic", "Recruitment", FormMethod.Post))
            {
                                                        <input type="hidden" name="email" value="@ViewBag.Email" />
                                                        <input type="hidden" name="link" value="@ViewBag.Link" />
                                                        <div class="form-group row">
                                                            <label class="col-lg-3 control-label">Upload</label>
                                                            <div class="col-lg-9">
                                                                <input type="file" class="form-control" name="file" />
                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <div class="col-lg-10">
                                                                <input type="hidden" />
                                                            </div>
                                                            <div class="col-lg-2">
                                                                <button type="button" class="btn btn-primary btn-xl" data-toggle="modal" data-target="#Modalalert">Save Changes</button>
                                                            </div>
                                                        </div>

                                                        <div class="modal fade" id="Modalalert" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                            <div class="modal-dialog" role="document">
                                                                <div class="modal-content">
                                                                    <div class="modal-header">
                                                                        <h5 class="modal-title" id="exampleModalLabel">Alert!</h5>
                                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                            <span aria-hidden="true">&times;</span>
                                                                        </button>
                                                                    </div>
                                                                    <div class="modal-body">
                                                                        Are u sure ?
                                                                    </div>
                                                                    <div class="modal-footer">
                                                                        <div class="form-group">
                                                                            <input type="submit" name="submit" value="Save" class="btn btn-secondary" />
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>

            }
        </div>
    </section>*@

<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalScrollableTitle">Read this before starting Logic Test</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                Use the most reliable Internet connection available!<br>
                If you lose network access or something goes wrong while taking a test and there is still time left to complete it,
                just refresh the page or return to your mail inbox and back into the test by clicking "Link to Assessment Page".
                You should be able to pick up where you left off.
                <br><br>
                Preserve your submission answers!<br>
                Focus only on one assessment at a time.
                Do not open multiple browser windows or tabs to take multiple assessments at the same time.
                Avoid Using Mobile Devices.
                Use a supported browser. Google Chrome, Internet Explorer, and Mozilla Firefox are supported browsers for this test, disable add-ons, and close unneeded applications.
                <br><br>
                By clicking Understood, it will be assumed that you have read this tips.
                Web page will be automatically directed to Nawa Data Logic Test and timer will start to countdown.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                @*<button onclick="window.open('@Url.Action("openviewpdf", "UploadLogicTestResult")')" class="btn btn-primary">Open Problems</button>*@
                @*<button class="btn btn-primary" type="button" id="addressSearch"
                    onclick="location.href='@Url.Action("List", "Search")'">*@
                <button class="btn btn-primary" type="button" data-dismiss="modal" onclick="location.href='@Url.Action("StartAndRedirect", "StartLogicTest", new {id = @ViewBag.ID, link = @ViewBag.Link})'">Understood</button>
                @*<a class="btn btn-primary" href="#form" onclick="$('#exampleModalScrollable').modal('hide')">Understood</a>*@
            </div>
        </div>
    </div>
</div>