nawadaya_project/Models/login.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nawadaya_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public long PK_userID { get; set; }
        public string role_name { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}

nawadaya_project/Controllers/LoginController.cs
using nawadaya_project.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace project_nawadaya.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            if (Session["hak_akses"] != null)
            {
                var hak = Session["hak_akses"].ToString();
                if (hak == "Admin")
                {
                    return RedirectToAction("Index", "HR");
                }
                else if (hak == "Super Admin")
                {
                    return RedirectToAction("Index", "RM");
                }
                else
                {
                    return RedirectToAction("Index", "Examiner");
                }
            }
            else
            {
                ViewBag.messagesuccess = TempData["messagesuccess"];
                ViewBag.ResetSuccess = TempData["ResetSuccess"];
                return View();
            }

        }

        private Nawadaya_Entities db = new Nawadaya_Entities();
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(login objUser)
        {
            if (ModelState.IsValid)
            {
                {
                    var password = md5(objUser.password);
                    var obj = (from s in db.logins where s.email.Equals(objUser.email) && s.password.Equals(password) select s).FirstOrDefault();
                    if (obj != null)
                    {
                        Session["UserID"] = obj.PK_userID.ToString();
                        Session["FullName"] = obj.full_name.ToString();
                        Session["Email"] = obj.email.ToString();
                        Session["UserName"] = obj.username.ToString();
                        Session["hak_akses"] = obj.role_name.ToString();
                        string hak = obj.role_name.ToString();
                        if (hak == "Admin")
                        {
                            return RedirectToAction("Index", "HR");
                        }
                        else if (hak == "Super Admin")
                        {
                            return RedirectToAction("Index", "RM");
                        }
                        else
                        {
                            return RedirectToAction("Index", "Examiner");
                        }
                    }
                    else
                    {
                        ViewBag.MessageUnknown = "User Unknown";
                        return View();
                    }
                }
            }
            return View(objUser);
        }

        [System.Web.Mvc.OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult Logoff(object sender, EventArgs e)
        {
            FormsAuthentication.SignOut();
            Session["UserName"] = null;
            Session.RemoveAll();
            Session.Abandon();

            return RedirectToAction("Index", "RM");
        }

        [HttpPost]
        public ActionResult Forgot(String email)
        {
            var email1 = email;
            var data = (from s in db.ms_personal_data where s.email.Equals(email1) select s.pk_employee).FirstOrDefault();
            var data2 = (from s in db.tbl_user where s.fk_employee == data select s).FirstOrDefault();
            if (data2 != null)
            {
                var key = "b14ca5898a4e4133bbce2ea2315a1916";
                var link = EncryptString(key, email);
                var fullname = db.ms_personal_data.Where(x => x.email == email).FirstOrDefault();
                var validation = SendEmail(email, link, fullname.full_name);
                if (validation == true)
                {

                    TempData["messagesuccess"] = 1;
                }
                else
                {
                    TempData["messagesuccess"] = 0;
                }
            }
            else {
                TempData["messagesuccess"] = 2;
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public bool SendEmail(string email, string link, string fullname)
        {
            MailMessage mm = new MailMessage("prewtry7@gmail.com", email);
            mm.From = new MailAddress("prewtry7@gmail.com", "Nawadaya");
            mm.Subject = "Forgot password";
            string tulisan = "<style>.button {background - color: #1c87c9;border: none;color: white;padding: 20px 34px;text - align: center;text - decoration: none;display: inline - block;font - size: 20px;margin: 4px 2px;cursor: pointer;}</style><b>Hi "+ fullname + ",</b><br>Someone requested a new password for your Nawadaya account. Click the button below to reset it.<br><br> <a class='button' href='http://localhost/Nawadaya2/Login/Reset?id=" + link + "'>Reset Password</a><br>If you didn't make this request then you can safely ignore this email.";
            mm.Body = tulisan;
            mm.IsBodyHtml = true;

            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.EnableSsl = true;

            NetworkCredential nc = new NetworkCredential("prewtry7@gmail.com", "husehusen");
            smtp.UseDefaultCredentials = true;
            smtp.Credentials = nc;
            try
            {
                smtp.Send(mm);
                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                RedirectToAction("NotFound", "OtherPage");
                return false;
            }

        }

        [HttpGet]
        public ActionResult Reset(string id)
        {
            if (Session["UserName"] != null)
            {
                RedirectToAction("Index");
            }
            
            
                id = id.Replace(" ", "+");
                var key = "b14ca5898a4e4133bbce2ea2315a1916";
                var email = DecryptString(key, id);
                var separate = email.Split('=');
                email = separate[0];
                long query = (from s in db.ms_personal_data where s.email.Equals(email) select s.pk_employee).FirstOrDefault();
                long query2 = (from s in db.tbl_user where s.fk_employee == query select s.pk_userID).FirstOrDefault();
                ViewBag.pk_userid = query2;
            ViewBag.id = id;
            ViewBag.messagesuccess = TempData["ResetSuccess"];
            return View();
            

            //return View();
        }

        //[HttpGet]
        //public ActionResult New_User(string id)
        //{
        //    if (Session["UserName"] != null)
        //    {
        //        RedirectToAction("Index");
        //    }
            
        //        id = id.Replace(" ", "+");
        //        var key = "b14ca5898a4e4133bbce2ea2315a1916";
        //        var email = DecryptString(key, id);
        //        var separate = email.Split('=');
        //        email = separate[0];
        //        long query = (from s in db.ms_personal_data where s.email.Equals(email) select s.pk_employee).FirstOrDefault();
        //        long query2 = (from s in db.tbl_user where s.fk_employee == query select s.pk_userID).FirstOrDefault();
        //        ViewBag.pk_userid = query2;
        //        return View();
            
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult new_user(tbl_user item)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var data = db.tbl_user.Find(item.pk_userID);
        //        var key = "b14ca5898a4e4133bbce2ea2315a1916";
        //        var password = EncryptString(key, string.Format("{0}", item.password));
        //        data.password = password;
        //        data.username = item.username;
        //        db.Entry(data).State = EntityState.Modified;
        //        db.SaveChanges();
        //        TempData["ResetSuccess"] = 2;
        //    }

        //    return RedirectToAction("Index");
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Reset(tbl_user item, string password2,string id)
        {
            using (DbContextTransaction transaction = db.Database.BeginTransaction())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        var data = db.tbl_user.Find(item.pk_userID);
                        var password = md5(item.password);
                        if (password == md5(password2))
                        {
                            data.password = password;
                            db.Entry(data).State = EntityState.Modified;
                            db.SaveChanges();
                            transaction.Commit();
                            TempData["ResetSuccess"] = 1;
                        }
                        else {
                            TempData["ResetSuccess"] = 2;
                            return Redirect("http://localhost/Nawadaya2/Login/Reset?id="+id);
                        }

                    }

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    transaction.Rollback();
                }
            }
            return RedirectToAction("Index");
        }

        static string md5(string input)
        { // Create a new instance of the MD5CryptoServiceProvider object.
            MD5 md5Hasher = MD5.Create(); // Convert the input string to a byte array and compute the hash.

nawadaya_project/Views/Login/Index.cshtml
@model nawadaya_project.Models.login
@{
    if (@ViewBag.MessageUnknown != null)
    {
        <script>
        function codeAddress() {
            $("#Alert1")
            .closest(".modal").modal('show');
        }
        window.onload = codeAddress;
        </script>
    }
    if (@ViewBag.messagesuccess != null)
    {
        <script>
        function codeAddress() {
            $("#messagemodal")
            .closest(".modal").modal('show');
            $('#messagemodal').on('hidden.bs.modal', function (e) {
                location.reload();
            });
        }
        window.onload = codeAddress;
        </script>
    }
    if (@ViewBag.ResetSuccess != null)
    {
        <script>
        function codeAddress() {
            $("#Alert2")
            .closest(".modal").modal('show');
            $('#Alert2').on('hidden.bs.modal', function (e) {
                location.reload();
            });
        }
        window.onload = codeAddress;
        </script>
    }
}
<div id="login-page">
    <div class="container">
        @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @class = "form-login" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <form>
                <h2 class="form-login-heading" style="background-color:#337ab7">sign in now</h2>
                <div class="login-wrap" style="border:solid">
                    @Html.TextBoxFor(a => a.email, new { @class = "form-control", required="required", type = "email", placeholder = "Email", autofocus = "autofocus" })
                    <br>
                    @Html.PasswordFor(a => a.password, new { @class = "form-control", required = "required", type = "password", placeholder = "password" })
                    <br>
                    <input class="btn btn-primary btn-block" type="submit" value="Login">
                    <hr>
                    <div class="registration">
                        <p class="message">Forgot Password? <a data-toggle="modal" href="login.html#myModal" class="elements">Click here!</a></p>
                    </div>
                </div>
                <!-- Modal -->
                <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="Alert1" class="modal fade">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Login</h4>
                            </div>
                            <div class="modal-body">
                                @*<p><b>Failed to log in.</b> Wrong username or password. Retry?</p> *@
                                <div class="alert alert-danger"><b>Failed to log in.</b> Wrong username or password.</div>
                            </div>
                            <div class="modal-footer">
                                <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="Alert2" class="modal fade">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Reset Password</h4>
                            </div>
                            <div class="modal-body">
                                <div class="alert alert-success"><b>Success!</b> Password is reset. Please login.</div>
                            </div>
                            <div class="modal-footer">
                                <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- modal -->
            </form>
        }
    </div>
</div>

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Forgot Password ?</h4>
            </div>
            <div class="modal-body">

                @using (Html.BeginForm("Forgot", "Login", FormMethod.Post))
                {
                    <p>Enter your e-mail address below to reset your password.</p>
                    <form class="form-login">
                        <input type="email" name="email" placeholder="Email" autocomplete="off" class="form-control placeholder-no-fix" />
                        <div class="modal-footer">
                            <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
                            <input class="btn btn-theme" type="submit" value="Submit" />
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</div>

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="messagemodal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Forgot Password</h4>
            </div>
            <div class="modal-body">
                @if (@ViewBag.messagesuccess != null)
                {
                if (@ViewBag.messagesuccess == 1)
                {
                <div class="alert alert-success"><b>Success!</b> Check your Email</div>
                }
                else if (@ViewBag.messagesuccess == 2)
                {
                <div class="alert alert-danger"><b>Failed!</b> This email doesn't belong to any user</div>
                }
                else if (@ViewBag.messagesuccess == 0)
                {
                <div class="alert alert-danger"><b>Failed!</b> Email is not sent</div>
                }
                else
                {
                <div class="alert alert-danger"><b>Failed!</b> Your email is invalid</div>
                }
                }

            </div>
        </div>
    </div>
</div>

nawadaya_project/Views/Login/New_User.cshtml
@model nawadaya_project.Models.tbl_user

<div id="login-page">
    <div class="container">
        @using (Html.BeginForm("new_user", "Login", FormMethod.Post, new { @class = "form-login" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <form>
                <h2 class="form-login-heading">Reset Password</h2>
                <div class="login-wrap">
                    @if (ViewBag.pk_userid != null)
                    {
                        @Html.PasswordFor(a => a.pk_userID, new { type = "hidden", value = ViewBag.pk_userid })
                    }
                    @Html.TextBoxFor(a => a.username, new { @class = "form-control", type = "text", placeholder = "New Username" })
                    <br>
                    @Html.PasswordFor(a => a.password, new { @class = "form-control", type = "password", placeholder = "New Password" })
                    <br>
                    <input class="btn btn-theme btn-block" type="submit" value="Login">
                </div>
            </form>
        }
    </div>
</div>

nawadaya_project/Views/Login/Reset.cshtml
@model nawadaya_project.Models.tbl_user
@{
    if (@ViewBag.MessageUnknown != null)
    {
        <script>
            function codeAddress() {
                $("#Alert1")
                    .closest(".modal").modal('show');
            }
            window.onload = codeAddress;
        </script>
    }
    if (@ViewBag.messagesuccess != null)
    {
        <script>
            function codeAddress() {
                $("#messagemodal")
                    .closest(".modal").modal('show');
                $('#messagemodal').on('hidden.bs.modal', function (e) {
                    location.reload();
                });
            }
            window.onload = codeAddress;
        </script>
    }
    if (@ViewBag.ResetSuccess != null)
    {
        <script>
            function codeAddress() {
                $("#Alert2")
                    .closest(".modal").modal('show');
                $('#Alert2').on('hidden.bs.modal', function (e) {
                    location.reload();
                });
            }
            window.onload = codeAddress;
        </script>
    }

}

<div id="login-page">
    <div class="container">
        @using (Html.BeginForm("Reset", "Login", FormMethod.Post, new { @class = "form-login" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <form>
                <h2 class="form-login-heading">Reset Password</h2>
                <div class="login-wrap">
                    @if (ViewBag.pk_userid != null)
                    {
                        @Html.PasswordFor(a => a.pk_userID, new { type = "hidden", value = ViewBag.pk_userid })
                    }
                    @Html.PasswordFor(a => a.password, new { @class = "form-control", type = "password", required="required", placeholder = "New Password" })
                    <br>
                    <input type="password" class="form-control" required placeholder="Re-input New Password" name="password2">
                    <input type="hidden" value="@ViewBag.id" name="id">
                    <br>
                    <input class="btn btn-theme btn-block" type="submit" value="Reset Password">
                </div>
            </form>
        }
    </div>
</div>

<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="messagemodal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Reset Password</h4>
            </div>
            <div class="modal-body">
                @if (@ViewBag.messagesuccess != null)
                {
                    if (@ViewBag.messagesuccess == 1)
                    {
                        <div class="alert alert-success"><b>Success!</b> Check your Email</div>
                    }
                    else if (@ViewBag.messagesuccess == 2)
                    {
                        <div class="alert alert-danger"><b>Failed!</b> Password not match</div>
                    }
                    else if (@ViewBag.messagesuccess == 0)
                    {
                        <div class="alert alert-danger"><b>Failed!</b> Email is not sent</div>
                    }
                    else
                    {
                        <div class="alert alert-danger"><b>Failed!</b> Your email is invalid</div>
                    }
                }

            </div>
        </div>
    </div>
</div>